version: "3"

services:
  nodeserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        APPLICATION_SOCKET: "http://localhost:5000"
        INTERFACE_LANGUAGE: "ru"
        DEV_SHOW_REDUCERS: "true"
        SHOW_TEST_SCHEMAS: "true"
        USE_DEVTOOLS: "true"
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 20s
